### PR TITLE
Add automatic version bumps

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Steps to do before merging this:

1. Register `bot@fragile.com` (bot email).
2. Register @fragile-bot user on GitHub using that email.
3. Generate a new GitHub token with access to public repos In the new account.
4. Add @fragile-bot to Guillemdb/fragile contributors ("Write" permissions)
5. Add the token generated in (3) to Travis CI environment variables as `FRAGILE_GITHUB_TOKEN`

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@Guillemdb You run two separate Travis builds. You should fix this in the repo settings. I think Travis was added in two different ways: the "modern" one and the "deprecated" one.

**Comment by Guillemdb** [comment]
@sergio-hcsoft I will need you to create the email. I can do the rest.

**Comment by vmarkovtsev** [comment]
I removed the webhook ("legacy" setup). Now we need to enable the repo at https://travis-ci.com/FragileTech/fragile but it does not show... Perhaps just need to wait a bit.

**Comment by vmarkovtsev** [comment]
OK, done.

**Comment by vmarkovtsev** [comment]
:tada: 
image

**Comment by vmarkovtsev** [comment]
@Guillemdb Py 3.6 failed: https://travis-ci.com/FragileTech/fragile/jobs/296291175#L461

**Comment by Guillemdb** [comment]
There is a test that fails ~5% of the time. I will let it run for more iterations so this stops happening. For some reason setting the random seed does not work.

**Comment by Guillemdb** [comment]
btw, @vmarkovtsev, I am registering the bot now.

**Comment by vmarkovtsev** [comment]
Does it always happen on 3.6 or floats across environments?

**Comment by Guillemdb** [comment]
Floats across env. The test is solving a cartpole environment with very few computational resources.

I was using this as an integration tests to make sure the fractal was working, but the computational budget is so low that it sometimes gets "unlucky". Once I am done with the bot I will fix it.

**Comment by vmarkovtsev** [comment]
It's interesting that it happens even though you fix the seed. There is some nasty entropy (hehe) left.

**Comment by Guillemdb** [comment]
I am pretty sure it's OpenAI `gym`'s fault. But I will run some checks later.

**Comment by Guillemdb** [comment]
The bot is configured. I am merging the PR.

**Comment by vmarkovtsev** [comment]
I restarted the failed test. Let's see...

For sure if there are flaky tests then the version automation will frequently fail.

**Pull request merged**
