### PR TITLE
Add pypi and dockerhub releases

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Steps to do before merging this:

1. Register FragileTech pypi account
2. Generate a [new API token in PyPi](https://pypi.org/help/#apitoken) and send it to Vadim
3. Vadim adds it in Travis

### CODE REVIEW

**Comment by Guillemdb** [comment]
Yeah, you are awesome!

 I will do the pypy regiatration tomorrow morning, but I wanna fix the remaining docs before the release.

**Comment by vmarkovtsev** [comment]
Let's see if everything is released without problems now. The actual package and image are easy to remove manually.

**Comment by vmarkovtsev** [comment]
Ditto

image

**Comment by vmarkovtsev** [comment]
```python
test $(python3 setup.py --version) == $TRAVIS_TAG
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from fragile.version import __version__
  File "/home/travis/build/FragileTech/fragile/fragile/__init__.py", line 2, in <module>
    from fragile.core.states import States
  File "/home/travis/build/FragileTech/fragile/fragile/core/__init__.py", line 2, in <module>
    from fragile.core.bounds import Bounds
  File "/home/travis/build/FragileTech/fragile/fragile/core/bounds.py", line 6, in <module>
    from fragile.core.utils import Scalar
  File "/home/travis/build/FragileTech/fragile/fragile/core/utils.py", line 5, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

`setup.py` should not import anything from the project except `version.py`

**Comment by vmarkovtsev** [comment]
https://github.com/FragileTech/fragile/pull/24

**Pull request merged**
