### PR TITLE
Fix atari-py installation

### PR DESCRIPTION
**Pull request by Guillemdb**
Closes https://github.com/FragileTech/fragile/issues/30

### CODE REVIEW

**Comment by Guillemdb** [comment]
@vmarkovtsev Should I fix it like this?

**Comment by vmarkovtsev** [comment]
@Guillemdb grep the CI log by `atari-py`

**Comment by Guillemdb** [comment]
I did. I am 80% sure it removes the default atari-py and installs ours (it installs the correct version for sure). Btw, how can we enable debug builds?

**Comment by vmarkovtsev** [comment]
@Guillemdb Nope, not fixed

```
Successfully built plangym atari-py setproctitle
Installing collected packages: atari-py, plangym, sortedcontainers, hypothesis, param, psycopg2-binary, pyarrow, setproctitle, joblib, scikit-learn, llvmlite, numba
  Attempting uninstall: atari-py
    Found existing installation: atari-py 0.1.1
    Uninstalling atari-py-0.1.1:
      Successfully uninstalled atari-py-0.1.1
  Attempting uninstall: plangym
    Found existing installation: plangym 0.0.1
    Can't uninstall 'plangym'. No files were found to uninstall.
Successfully installed atari-py-0.1.1 hypothesis-5.6.0 joblib-0.14.1 llvmlite-0.31.0 numba-0.48.0 param-1.9.3 plangym-0.0.1 
```

**Comment by Guillemdb** [comment]
I'm trying again

**Pull request merged**
